### PR TITLE
Update BluetoothConnect.ino

### PR DESCRIPTION
**Pull request by fxswe**
## Related issue(s)
#26 #35

### CODE REVIEW

**Review by flyslowly — APPROVED** [review]
Reviewed integrating line following with Bluetooth control

**Comment by platisd** [comment]
Why do you have so many Arduino sketches? Are you working towards integrating the functionality?

**Comment by fxswe** [comment]
The reason that we have many different arduino sketches is that we are working on many different functionalities. We want to test the different function independently and when we are sure that they work we want to merge them into one arduino sketch.

**Comment by platisd** [comment]
OK, but please work as soon as possible towards that goal! :+1:

**Pull request merged**
